/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// ErrorCodeResourceNotFound is the error code RESOURCE_NOT_FOUND.
//
// The requested resource could not be found.
// Typical HTTP status: 404.
const ErrorCodeResourceNotFound ErrorCode = "RESOURCE_NOT_FOUND"

// ErrorCodeValidationError is the error code VALIDATION_ERROR.
//
// One or more request fields are invalid or incompatible.
// Typical HTTP status: 400.
const ErrorCodeValidationError ErrorCode = "VALIDATION_ERROR"

// ErrorCodeRequiredFieldMissing is the error code REQUIRED_FIELD_MISSING.
//
// A required request field was not provided.
// Typical HTTP status: 400.
const ErrorCodeRequiredFieldMissing ErrorCode = "REQUIRED_FIELD_MISSING"

// ErrorCodeFailedPrecondition is the error code FAILED_PRECONDITION.
//
// The request could not be completed because a required precondition was not met.
// Typical HTTP status: 400.
const ErrorCodeFailedPrecondition ErrorCode = "FAILED_PRECONDITION"

// ErrorCodeAuthenticationFailed is the error code AUTHENTICATION_FAILED.
//
// The request could not be authenticated. Check that the credentials supplied with
// the request are valid.
// Typical HTTP status: 401.
const ErrorCodeAuthenticationFailed ErrorCode = "AUTHENTICATION_FAILED"

// ErrorCodePermissionDenied is the error code PERMISSION_DENIED.
//
// You do not have permission to perform this action with the current API key.
// Typical HTTP status: 403.
const ErrorCodePermissionDenied ErrorCode = "PERMISSION_DENIED"

// ErrorCodeRateLimitExceeded is the error code RATE_LIMIT_EXCEEDED.
//
// You have exceeded the request rate limit. Reduce your request rate and retry
// after a backoff period.
// Typical HTTP status: 429.
const ErrorCodeRateLimitExceeded ErrorCode = "RATE_LIMIT_EXCEEDED"

// ErrorCodeInternalError is the error code INTERNAL_ERROR.
//
// An unexpected internal error occurred while processing the request. If this
// persists, contact support.
// Typical HTTP status: 500.
const ErrorCodeInternalError ErrorCode = "INTERNAL_ERROR"

// ErrorCodeNotImplemented is the error code NOT_IMPLEMENTED.
//
// This endpoint or operation is not yet implemented.
// Typical HTTP status: 501.
const ErrorCodeNotImplemented ErrorCode = "NOT_IMPLEMENTED"

// ErrorCodeServiceUnavailable is the error code SERVICE_UNAVAILABLE.
//
// The service is temporarily unavailable. Retry the request after a backoff
// period.
// Typical HTTP status: 503.
const ErrorCodeServiceUnavailable ErrorCode = "SERVICE_UNAVAILABLE"
