/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeTransactionNotFound is the subcode TRANSACTION_NOT_FOUND.
//
// The requested transaction could not be found for this portfolio, or a
// transaction referenced in transaction_ids does not belong to it.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeTransactionNotFound Subcode = "TRANSACTION_NOT_FOUND"

// SubcodeTransactionTravelRuleDataNotFound is the subcode TRANSACTION_TRAVEL_RULE_DATA_NOT_FOUND.
//
// No travel rule data is available for the specified transaction.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeTransactionTravelRuleDataNotFound Subcode = "TRANSACTION_TRAVEL_RULE_DATA_NOT_FOUND"

// SubcodeTransactionTypeUnsupported is the subcode TRANSACTION_TYPE_UNSUPPORTED.
//
// The transaction does not support the requested operation, such as submitting
// travel rule data for a transaction that is not a deposit.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionTypeUnsupported Subcode = "TRANSACTION_TYPE_UNSUPPORTED"

// SubcodeTransactionTravelRulePartyInvalid is the subcode TRANSACTION_TRAVEL_RULE_PARTY_INVALID.
//
// The originator or beneficiary information provided for the travel rule
// submission is missing or fails identity validation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionTravelRulePartyInvalid Subcode = "TRANSACTION_TRAVEL_RULE_PARTY_INVALID"

// SubcodeTransactionIdRequired is the subcode TRANSACTION_ID_REQUIRED.
//
// The transaction_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeTransactionIdRequired Subcode = "TRANSACTION_ID_REQUIRED"

// SubcodeTransactionIdInvalid is the subcode TRANSACTION_ID_INVALID.
//
// The transaction_id field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionIdInvalid Subcode = "TRANSACTION_ID_INVALID"

// SubcodeTransactionLimitExceeded is the subcode TRANSACTION_LIMIT_EXCEEDED.
//
// The limit field exceeds the maximum number of transactions that can be returned
// in a single request.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionLimitExceeded Subcode = "TRANSACTION_LIMIT_EXCEEDED"

// SubcodeTransactionServiceUnavailable is the subcode TRANSACTION_SERVICE_UNAVAILABLE.
//
// The transaction data needed to fulfill this request is temporarily unavailable.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeTransactionServiceUnavailable Subcode = "TRANSACTION_SERVICE_UNAVAILABLE"

// SubcodeTransactionCursorInvalid is the subcode TRANSACTION_CURSOR_INVALID.
//
// The cursor field is not a valid pagination token. Omit it or use the cursor
// value returned from a previous response.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionCursorInvalid Subcode = "TRANSACTION_CURSOR_INVALID"

// SubcodeTransactionTravelRuleStatusInvalid is the subcode TRANSACTION_TRAVEL_RULE_STATUS_INVALID.
//
// The travel_rule_status filter contains a value that is not recognized.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionTravelRuleStatusInvalid Subcode = "TRANSACTION_TRAVEL_RULE_STATUS_INVALID"

// SubcodeTransactionFilterInvalid is the subcode TRANSACTION_FILTER_INVALID.
//
// The combination of request filters is invalid, such as specifying symbols
// together with the ONCHAIN_TRANSACTION type.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionFilterInvalid Subcode = "TRANSACTION_FILTER_INVALID"

// SubcodeTransactionIdsInvalid is the subcode TRANSACTION_IDS_INVALID.
//
// One or more values in transaction_ids are missing, exceed the maximum allowed
// count, or are not valid UUIDs.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionIdsInvalid Subcode = "TRANSACTION_IDS_INVALID"

// SubcodeTransactionParamsInvalid is the subcode TRANSACTION_PARAMS_INVALID.
//
// One or more request parameters, such as portfolio_id, transaction_ids, cursor,
// or limit, failed validation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTransactionParamsInvalid Subcode = "TRANSACTION_PARAMS_INVALID"
