/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeAuthAuthorizationFailed is the subcode AUTH_AUTHORIZATION_FAILED.
//
// An unexpected error occurred while authorizing the request. If this persists,
// contact support.
// HTTP status: 500. Error code: INTERNAL_ERROR.
const SubcodeAuthAuthorizationFailed Subcode = "AUTH_AUTHORIZATION_FAILED"

// SubcodeAuthResourceAccessDenied is the subcode AUTH_RESOURCE_ACCESS_DENIED.
//
// You do not have permission to access this resource with the current API key.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeAuthResourceAccessDenied Subcode = "AUTH_RESOURCE_ACCESS_DENIED"

// SubcodeAuthResourceNotFound is the subcode AUTH_RESOURCE_NOT_FOUND.
//
// No resource was found matching the request, or you do not have access to it.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeAuthResourceNotFound Subcode = "AUTH_RESOURCE_NOT_FOUND"

// SubcodeAuthUnauthenticated is the subcode AUTH_UNAUTHENTICATED.
//
// The request could not be authenticated. Check that the credentials supplied with
// the request are valid.
// HTTP status: 401. Error code: AUTHENTICATION_FAILED.
const SubcodeAuthUnauthenticated Subcode = "AUTH_UNAUTHENTICATED"

// SubcodeEndpointNotImplemented is the subcode ENDPOINT_NOT_IMPLEMENTED.
//
// This endpoint is not yet implemented.
// HTTP status: 501. Error code: NOT_IMPLEMENTED.
const SubcodeEndpointNotImplemented Subcode = "ENDPOINT_NOT_IMPLEMENTED"

// SubcodeServerMaintenanceModeActive is the subcode SERVER_MAINTENANCE_MODE_ACTIVE.
//
// The API is currently in maintenance mode and not accepting this request.
// Maintenance windows can be extended; check https://status.prime.coinbase.com
// before retrying.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeServerMaintenanceModeActive Subcode = "SERVER_MAINTENANCE_MODE_ACTIVE"

// SubcodeServerRateLimitExceeded is the subcode SERVER_RATE_LIMIT_EXCEEDED.
//
// You have exceeded the request rate limit for this endpoint. Reduce your request
// rate and retry after a backoff period.
// HTTP status: 429. Error code: RATE_LIMIT_EXCEEDED.
const SubcodeServerRateLimitExceeded Subcode = "SERVER_RATE_LIMIT_EXCEEDED"

// SubcodeMtlsCertificateRequired is the subcode MTLS_CERTIFICATE_REQUIRED.
//
// A valid client certificate was not presented with the request.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeMtlsCertificateRequired Subcode = "MTLS_CERTIFICATE_REQUIRED"

// SubcodeMtlsCertificateRevoked is the subcode MTLS_CERTIFICATE_REVOKED.
//
// The presented client certificate has been revoked.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeMtlsCertificateRevoked Subcode = "MTLS_CERTIFICATE_REVOKED"

// SubcodeMtlsCertificateInvalid is the subcode MTLS_CERTIFICATE_INVALID.
//
// The presented client certificate is not a valid identity for this organization
// or environment.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeMtlsCertificateInvalid Subcode = "MTLS_CERTIFICATE_INVALID"

// SubcodeApiKeyInvalidDuration is the subcode API_KEY_INVALID_DURATION.
//
// The duration_seconds field exceeds the maximum allowed rotation timespan of 30
// days.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeApiKeyInvalidDuration Subcode = "API_KEY_INVALID_DURATION"

// SubcodeApiKeyAlreadyRotated is the subcode API_KEY_ALREADY_ROTATED.
//
// A rotation has already been initiated for this API key. Only one rotation may be
// pending at a time.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeApiKeyAlreadyRotated Subcode = "API_KEY_ALREADY_ROTATED"
