/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeOrderIdRequired is the subcode ORDER_ID_REQUIRED.
//
// The order_id field is missing from the request.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderIdRequired Subcode = "ORDER_ID_REQUIRED"

// SubcodeOrderIdInvalid is the subcode ORDER_ID_INVALID.
//
// The order_id provided is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderIdInvalid Subcode = "ORDER_ID_INVALID"

// SubcodeOrderNotFound is the subcode ORDER_NOT_FOUND.
//
// No order was found matching the provided order_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeOrderNotFound Subcode = "ORDER_NOT_FOUND"

// SubcodeOrderRequestInvalid is the subcode ORDER_REQUEST_INVALID.
//
// The order request failed validation, such as an invalid stp_id, price, size, or
// commission_rate.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderRequestInvalid Subcode = "ORDER_REQUEST_INVALID"

// SubcodeOrderStatusInvalid is the subcode ORDER_STATUS_INVALID.
//
// The requested order_status values include non-terminal statuses (such as OPEN or
// PENDING), which this endpoint does not support. Use the Open Orders endpoint, or
// the Websocket/FIX API, to retrieve non-terminal orders.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderStatusInvalid Subcode = "ORDER_STATUS_INVALID"

// SubcodeOrderLimitExceeded is the subcode ORDER_LIMIT_EXCEEDED.
//
// The query would return more results than this endpoint allows. Narrow the query
// or use the Websocket API for a full stream of results.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderLimitExceeded Subcode = "ORDER_LIMIT_EXCEEDED"

// SubcodeOrderFillsLimitInvalid is the subcode ORDER_FILLS_LIMIT_INVALID.
//
// The limit field for a fills query is outside the allowed range of 1 to 3000.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderFillsLimitInvalid Subcode = "ORDER_FILLS_LIMIT_INVALID"

// SubcodeOrderFillsStartDateRequired is the subcode ORDER_FILLS_START_DATE_REQUIRED.
//
// The start_date field is required for this fills query.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderFillsStartDateRequired Subcode = "ORDER_FILLS_START_DATE_REQUIRED"

// SubcodeOrderFillsStartDateInvalid is the subcode ORDER_FILLS_START_DATE_INVALID.
//
// The start_date field is not a valid timestamp.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderFillsStartDateInvalid Subcode = "ORDER_FILLS_START_DATE_INVALID"

// SubcodeOrderFillsEndDateInvalid is the subcode ORDER_FILLS_END_DATE_INVALID.
//
// The end_date field is not a valid timestamp.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderFillsEndDateInvalid Subcode = "ORDER_FILLS_END_DATE_INVALID"

// SubcodeOrderTypeBlockUnsupported is the subcode ORDER_TYPE_BLOCK_UNSUPPORTED.
//
// Orders of type BLOCK cannot be created or previewed through this endpoint.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderTypeBlockUnsupported Subcode = "ORDER_TYPE_BLOCK_UNSUPPORTED"

// SubcodeOrderTypeRfqUnsupported is the subcode ORDER_TYPE_RFQ_UNSUPPORTED.
//
// Orders of type RFQ cannot be created or previewed through this endpoint. Use the
// RFQ (/rfq) and accept quote (/accept_quote) endpoints instead.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderTypeRfqUnsupported Subcode = "ORDER_TYPE_RFQ_UNSUPPORTED"

// SubcodeOrderFokNotEnabled is the subcode ORDER_FOK_NOT_ENABLED.
//
// The FILL_OR_KILL time-in-force is not enabled for this portfolio.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderFokNotEnabled Subcode = "ORDER_FOK_NOT_ENABLED"

// SubcodeOrderStopLimitNotEnabled is the subcode ORDER_STOP_LIMIT_NOT_ENABLED.
//
// STOP_LIMIT orders are not enabled for this portfolio.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderStopLimitNotEnabled Subcode = "ORDER_STOP_LIMIT_NOT_ENABLED"

// SubcodeOrderPegNotEnabled is the subcode ORDER_PEG_NOT_ENABLED.
//
// PEG orders are not enabled for this portfolio.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderPegNotEnabled Subcode = "ORDER_PEG_NOT_ENABLED"

// SubcodeOrderDuplicateClientOrderId is the subcode ORDER_DUPLICATE_CLIENT_ORDER_ID.
//
// An order with this client_order_id already exists. Use a unique client_order_id
// for each new order.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderDuplicateClientOrderId Subcode = "ORDER_DUPLICATE_CLIENT_ORDER_ID"

// SubcodeOrderRejected is the subcode ORDER_REJECTED.
//
// The order was rejected during processing and was not placed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderRejected Subcode = "ORDER_REJECTED"

// SubcodeOrderProductIdInvalid is the subcode ORDER_PRODUCT_ID_INVALID.
//
// The product_id is not a valid or currently tradable product for this request.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderProductIdInvalid Subcode = "ORDER_PRODUCT_ID_INVALID"

// SubcodeOrderTypeNotAllowed is the subcode ORDER_TYPE_NOT_ALLOWED.
//
// The requested order type is not allowed on this endpoint (for example, BLOCK or
// RFQ orders submitted via CreateOrder).
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderTypeNotAllowed Subcode = "ORDER_TYPE_NOT_ALLOWED"

// SubcodeOrderTifNotEnabled is the subcode ORDER_TIF_NOT_ENABLED.
//
// The requested time_in_force (such as FILL_OR_KILL) is not enabled for this
// portfolio.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderTifNotEnabled Subcode = "ORDER_TIF_NOT_ENABLED"

// SubcodeOrderFailedPrecondition is the subcode ORDER_FAILED_PRECONDITION.
//
// The order request could not be completed because a required precondition was not
// met, for example an account needed to process the order could not be found or
// created.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeOrderFailedPrecondition Subcode = "ORDER_FAILED_PRECONDITION"

// SubcodeOrderServiceUnavailable is the subcode ORDER_SERVICE_UNAVAILABLE.
//
// The trading service needed to process this order request is temporarily
// unavailable.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeOrderServiceUnavailable Subcode = "ORDER_SERVICE_UNAVAILABLE"

// SubcodeOrderRfqNotEnabled is the subcode ORDER_RFQ_NOT_ENABLED.
//
// This portfolio is not allowed to submit RFQ (request-for-quote) requests.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeOrderRfqNotEnabled Subcode = "ORDER_RFQ_NOT_ENABLED"

// SubcodeOrderCancelNotAllowed is the subcode ORDER_CANCEL_NOT_ALLOWED.
//
// This order is not allowed to be canceled.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeOrderCancelNotAllowed Subcode = "ORDER_CANCEL_NOT_ALLOWED"

// SubcodeOrderFullyFilled is the subcode ORDER_FULLY_FILLED.
//
// The order is fully filled and can no longer be canceled.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeOrderFullyFilled Subcode = "ORDER_FULLY_FILLED"

// SubcodeOrderBeingReplaced is the subcode ORDER_BEING_REPLACED.
//
// The order is currently being replaced (edited) and cannot be canceled while that
// is in progress.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeOrderBeingReplaced Subcode = "ORDER_BEING_REPLACED"

// SubcodeOrderCancelDuplicate is the subcode ORDER_CANCEL_DUPLICATE.
//
// A cancel request for this order has already been submitted and is still being
// processed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderCancelDuplicate Subcode = "ORDER_CANCEL_DUPLICATE"

// SubcodeOrderSessionInvalid is the subcode ORDER_SESSION_INVALID.
//
// The FCM trading session associated with this order is not valid for the
// requested cancel operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderSessionInvalid Subcode = "ORDER_SESSION_INVALID"

// SubcodeOrderProductIdRequired is the subcode ORDER_PRODUCT_ID_REQUIRED.
//
// The product_id field is required for this request.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderProductIdRequired Subcode = "ORDER_PRODUCT_ID_REQUIRED"

// SubcodeOrderClientOrderIdRequired is the subcode ORDER_CLIENT_ORDER_ID_REQUIRED.
//
// The client_order_id field is required to accept a quote.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderClientOrderIdRequired Subcode = "ORDER_CLIENT_ORDER_ID_REQUIRED"

// SubcodeOrderQuoteIdRequired is the subcode ORDER_QUOTE_ID_REQUIRED.
//
// The quote_id field is required to accept a quote.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderQuoteIdRequired Subcode = "ORDER_QUOTE_ID_REQUIRED"

// SubcodeOrderSideRequired is the subcode ORDER_SIDE_REQUIRED.
//
// The side field is required and was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderSideRequired Subcode = "ORDER_SIDE_REQUIRED"

// SubcodeOrderResourceNotFound is the subcode ORDER_RESOURCE_NOT_FOUND.
//
// No order matching the given order_id was found for this portfolio.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderResourceNotFound Subcode = "ORDER_RESOURCE_NOT_FOUND"

// SubcodeOrderSideInvalid is the subcode ORDER_SIDE_INVALID.
//
// The side field is not a supported order side. Specify BUY or SELL.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderSideInvalid Subcode = "ORDER_SIDE_INVALID"

// SubcodeOrderSizeRequired is the subcode ORDER_SIZE_REQUIRED.
//
// The order size is missing. Specify either base_quantity or quote_value.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderSizeRequired Subcode = "ORDER_SIZE_REQUIRED"

// SubcodeOrderSizeInvalid is the subcode ORDER_SIZE_INVALID.
//
// The order size is invalid, either because it could not be parsed as a number or
// because both base_quantity and quote_value were specified.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderSizeInvalid Subcode = "ORDER_SIZE_INVALID"

// SubcodeOrderDisplaySizeInvalid is the subcode ORDER_DISPLAY_SIZE_INVALID.
//
// The display size is invalid, either because both display size fields were
// specified or because the display size field does not match the currency of the
// order size.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderDisplaySizeInvalid Subcode = "ORDER_DISPLAY_SIZE_INVALID"

// SubcodeOrderPriceInvalid is the subcode ORDER_PRICE_INVALID.
//
// The order price is invalid, either because limit_price could not be parsed as a
// number or because a limit price was supplied for a market order.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderPriceInvalid Subcode = "ORDER_PRICE_INVALID"

// SubcodeOrderStopPriceInvalid is the subcode ORDER_STOP_PRICE_INVALID.
//
// The stop_price for a STOP_LIMIT order is missing or could not be parsed as a
// number.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderStopPriceInvalid Subcode = "ORDER_STOP_PRICE_INVALID"

// SubcodeOrderTimeInForceInvalid is the subcode ORDER_TIME_IN_FORCE_INVALID.
//
// The time_in_force value is not compatible with the requested order type or
// post-only flag.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderTimeInForceInvalid Subcode = "ORDER_TIME_IN_FORCE_INVALID"

// SubcodeOrderTimeRangeInvalid is the subcode ORDER_TIME_RANGE_INVALID.
//
// The order is missing a start_time or end_time required for its order type or
// time-in-force.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderTimeRangeInvalid Subcode = "ORDER_TIME_RANGE_INVALID"

// SubcodeOrderPegOffsetTypeInvalid is the subcode ORDER_PEG_OFFSET_TYPE_INVALID.
//
// The peg_offset_type is not a supported value for a PEG order.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderPegOffsetTypeInvalid Subcode = "ORDER_PEG_OFFSET_TYPE_INVALID"

// SubcodeOrderClientQuoteIdRequired is the subcode ORDER_CLIENT_QUOTE_ID_REQUIRED.
//
// The client_quote_id field is required for a quote request.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOrderClientQuoteIdRequired Subcode = "ORDER_CLIENT_QUOTE_ID_REQUIRED"

// SubcodeOrderQuoteDurationInvalid is the subcode ORDER_QUOTE_DURATION_INVALID.
//
// The quote_duration_ms field is outside the allowed range.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOrderQuoteDurationInvalid Subcode = "ORDER_QUOTE_DURATION_INVALID"

// SubcodeOrderRfqSiqNotEnabled is the subcode ORDER_RFQ_SIQ_NOT_ENABLED.
//
// Size-in-quote RFQ requests are not enabled for this portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeOrderRfqSiqNotEnabled Subcode = "ORDER_RFQ_SIQ_NOT_ENABLED"
