/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeCandleRequestInvalid is the subcode CANDLE_REQUEST_INVALID.
//
// The request for candle data is invalid because a field, such as start_time or
// end_time, is missing or malformed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeCandleRequestInvalid Subcode = "CANDLE_REQUEST_INVALID"

// SubcodeCandleTimeRangeInvalid is the subcode CANDLE_TIME_RANGE_INVALID.
//
// The requested start_time and end_time combination is not a valid candle time
// range for the given granularity.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeCandleTimeRangeInvalid Subcode = "CANDLE_TIME_RANGE_INVALID"

// SubcodeProductFuturesNotEnabled is the subcode PRODUCT_FUTURES_NOT_ENABLED.
//
// Futures products are not enabled for the specified portfolio_id.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeProductFuturesNotEnabled Subcode = "PRODUCT_FUTURES_NOT_ENABLED"

// SubcodeProductNotFound is the subcode PRODUCT_NOT_FOUND.
//
// No products were found matching the requested criteria.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeProductNotFound Subcode = "PRODUCT_NOT_FOUND"

// SubcodeProductLimitInvalid is the subcode PRODUCT_LIMIT_INVALID.
//
// The limit field must be a positive number.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeProductLimitInvalid Subcode = "PRODUCT_LIMIT_INVALID"

// SubcodeProductOptionsNotEnabled is the subcode PRODUCT_OPTIONS_NOT_ENABLED.
//
// Options products are not enabled for the specified portfolio_id.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeProductOptionsNotEnabled Subcode = "PRODUCT_OPTIONS_NOT_ENABLED"

// SubcodeMarketDataInvalidArgument is the subcode MARKET_DATA_INVALID_ARGUMENT.
//
// The request contained an invalid argument, such as an unrecognized entity_id,
// cursor, or sort_direction.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeMarketDataInvalidArgument Subcode = "MARKET_DATA_INVALID_ARGUMENT"

// SubcodeMarketDataNotFound is the subcode MARKET_DATA_NOT_FOUND.
//
// No market data was found for the given entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeMarketDataNotFound Subcode = "MARKET_DATA_NOT_FOUND"
