/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeAdvancedTransferNotEnabled is the subcode ADVANCED_TRANSFER_NOT_ENABLED.
//
// Advanced Transfers are not enabled for this portfolio, or the specific transfer
// configuration requested is not enabled for this portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeAdvancedTransferNotEnabled Subcode = "ADVANCED_TRANSFER_NOT_ENABLED"

// SubcodeAdvancedTransferRequestInvalid is the subcode ADVANCED_TRANSFER_REQUEST_INVALID.
//
// The advanced transfer request is malformed or fails validation, such as a
// missing portfolio_id, a missing or unsupported transfer type, or an invalid fund
// movement.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAdvancedTransferRequestInvalid Subcode = "ADVANCED_TRANSFER_REQUEST_INVALID"

// SubcodeAdvancedTransferIdInvalid is the subcode ADVANCED_TRANSFER_ID_INVALID.
//
// The advanced_transfer_id provided does not correspond to a transfer that can be
// cancelled.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAdvancedTransferIdInvalid Subcode = "ADVANCED_TRANSFER_ID_INVALID"

// SubcodeAdvancedTransferCancelPreconditionFailed is the subcode ADVANCED_TRANSFER_CANCEL_PRECONDITION_FAILED.
//
// The advanced transfer cannot be cancelled because it is no longer in a
// cancellable state.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeAdvancedTransferCancelPreconditionFailed Subcode = "ADVANCED_TRANSFER_CANCEL_PRECONDITION_FAILED"

// SubcodeAdvancedTransferPreconditionFailed is the subcode ADVANCED_TRANSFER_PRECONDITION_FAILED.
//
// The advanced transfer cannot be processed because a precondition was not met,
// such as no wallet being available in the portfolio for one of the fund movement
// currencies.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeAdvancedTransferPreconditionFailed Subcode = "ADVANCED_TRANSFER_PRECONDITION_FAILED"

// SubcodeAdvancedTransferServiceUnavailable is the subcode ADVANCED_TRANSFER_SERVICE_UNAVAILABLE.
//
// The service needed to process this advanced transfer request is currently
// unavailable or has reached a rate limit.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeAdvancedTransferServiceUnavailable Subcode = "ADVANCED_TRANSFER_SERVICE_UNAVAILABLE"

// SubcodeAdvancedTransferDateInvalid is the subcode ADVANCED_TRANSFER_DATE_INVALID.
//
// The settlement_date, settlement_time, or trade_date field is not in the expected
// format.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAdvancedTransferDateInvalid Subcode = "ADVANCED_TRANSFER_DATE_INVALID"

// SubcodeAdvancedTransferNotFound is the subcode ADVANCED_TRANSFER_NOT_FOUND.
//
// A resource referenced by the advanced transfer request could not be found.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeAdvancedTransferNotFound Subcode = "ADVANCED_TRANSFER_NOT_FOUND"

// SubcodeAdvancedTransferTooManyFundMovements is the subcode ADVANCED_TRANSFER_TOO_MANY_FUND_MOVEMENTS.
//
// The advanced transfer includes more fund movements than the maximum number of
// legs allowed per transfer.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAdvancedTransferTooManyFundMovements Subcode = "ADVANCED_TRANSFER_TOO_MANY_FUND_MOVEMENTS"

// SubcodeAdvancedTransferCounterpartyInvalid is the subcode ADVANCED_TRANSFER_COUNTERPARTY_INVALID.
//
// The fund movements in this advanced transfer do not all settle against the same
// counterparty; all legs must share a single counterparty.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAdvancedTransferCounterpartyInvalid Subcode = "ADVANCED_TRANSFER_COUNTERPARTY_INVALID"

// SubcodeAdvancedTransferAmountInvalid is the subcode ADVANCED_TRANSFER_AMOUNT_INVALID.
//
// The amount on one or more fund movements is not a valid positive decimal value.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAdvancedTransferAmountInvalid Subcode = "ADVANCED_TRANSFER_AMOUNT_INVALID"

// SubcodeAdvancedTransferCounterpartyRequired is the subcode ADVANCED_TRANSFER_COUNTERPARTY_REQUIRED.
//
// One or more fund movements is missing its counterparty identifier.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAdvancedTransferCounterpartyRequired Subcode = "ADVANCED_TRANSFER_COUNTERPARTY_REQUIRED"
