/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeAssetNotFound is the subcode ASSET_NOT_FOUND.
//
// The requested asset could not be found, for example because the currency symbol
// or asset identifier does not correspond to a supported asset.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeAssetNotFound Subcode = "ASSET_NOT_FOUND"

// SubcodeAssetRequestInvalid is the subcode ASSET_REQUEST_INVALID.
//
// The asset lookup request contains an invalid argument, such as an unsupported
// currency symbol or malformed asset identifier.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAssetRequestInvalid Subcode = "ASSET_REQUEST_INVALID"

// SubcodeAssetServiceUnavailable is the subcode ASSET_SERVICE_UNAVAILABLE.
//
// Asset information could not be retrieved at this time.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeAssetServiceUnavailable Subcode = "ASSET_SERVICE_UNAVAILABLE"
