/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeFcmBalanceNotFound is the subcode FCM_BALANCE_NOT_FOUND.
//
// No futures balance data was found for the given entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeFcmBalanceNotFound Subcode = "FCM_BALANCE_NOT_FOUND"

// SubcodeFcmInvalidArgument is the subcode FCM_INVALID_ARGUMENT.
//
// The request contained an invalid argument for this futures operation, such as an
// unrecognized entity_id or an invalid amount or currency.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFcmInvalidArgument Subcode = "FCM_INVALID_ARGUMENT"

// SubcodeFcmEquityNotFound is the subcode FCM_EQUITY_NOT_FOUND.
//
// No end-of-day equity data was found for the futures account associated with the
// given entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeFcmEquityNotFound Subcode = "FCM_EQUITY_NOT_FOUND"

// SubcodeFcmRiskLimitsNotFound is the subcode FCM_RISK_LIMITS_NOT_FOUND.
//
// No risk limit data was found for the futures account associated with the given
// entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeFcmRiskLimitsNotFound Subcode = "FCM_RISK_LIMITS_NOT_FOUND"

// SubcodeFcmSweepNotFound is the subcode FCM_SWEEP_NOT_FOUND.
//
// No sweep request was found for the given entity_id, including when there is no
// pending sweep available to cancel.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeFcmSweepNotFound Subcode = "FCM_SWEEP_NOT_FOUND"

// SubcodeFcmSweepCurrencyRequired is the subcode FCM_SWEEP_CURRENCY_REQUIRED.
//
// The currency field is required when scheduling a futures sweep.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeFcmSweepCurrencyRequired Subcode = "FCM_SWEEP_CURRENCY_REQUIRED"

// SubcodeFcmTargetDerivativesExcessInvalid is the subcode FCM_TARGET_DERIVATIVES_EXCESS_INVALID.
//
// The target_derivatives_excess field must be a valid, non-negative decimal value.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFcmTargetDerivativesExcessInvalid Subcode = "FCM_TARGET_DERIVATIVES_EXCESS_INVALID"

// SubcodeFcmAccountNotFound is the subcode FCM_ACCOUNT_NOT_FOUND.
//
// No futures (FCM) account is configured for the given entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeFcmAccountNotFound Subcode = "FCM_ACCOUNT_NOT_FOUND"
