/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeAllocationIdRequired is the subcode ALLOCATION_ID_REQUIRED.
//
// The allocation_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAllocationIdRequired Subcode = "ALLOCATION_ID_REQUIRED"

// SubcodeAllocationIdInvalid is the subcode ALLOCATION_ID_INVALID.
//
// The allocation_id field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationIdInvalid Subcode = "ALLOCATION_ID_INVALID"

// SubcodeAllocationNotFound is the subcode ALLOCATION_NOT_FOUND.
//
// The requested allocation could not be found, either because it does not exist or
// because the orders being allocated could not be retrieved.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeAllocationNotFound Subcode = "ALLOCATION_NOT_FOUND"

// SubcodeAllocationNettingIdRequired is the subcode ALLOCATION_NETTING_ID_REQUIRED.
//
// The netting_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAllocationNettingIdRequired Subcode = "ALLOCATION_NETTING_ID_REQUIRED"

// SubcodeAllocationNettingIdInvalid is the subcode ALLOCATION_NETTING_ID_INVALID.
//
// The netting_id field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationNettingIdInvalid Subcode = "ALLOCATION_NETTING_ID_INVALID"

// SubcodeAllocationRequestInvalid is the subcode ALLOCATION_REQUEST_INVALID.
//
// One or more allocation request fields, such as product_id, order_ids,
// allocation_legs, or size_type, are missing or invalid.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationRequestInvalid Subcode = "ALLOCATION_REQUEST_INVALID"

// SubcodeAllocationStartDateRequired is the subcode ALLOCATION_START_DATE_REQUIRED.
//
// The start_date field is required when listing portfolio allocations.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAllocationStartDateRequired Subcode = "ALLOCATION_START_DATE_REQUIRED"

// SubcodeAllocationPreconditionFailed is the subcode ALLOCATION_PRECONDITION_FAILED.
//
// The allocation could not be processed because buying power or account
// information for the source or destination portfolio could not be retrieved.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeAllocationPreconditionFailed Subcode = "ALLOCATION_PRECONDITION_FAILED"

// SubcodeAllocationSourcePortfolioIdRequired is the subcode ALLOCATION_SOURCE_PORTFOLIO_ID_REQUIRED.
//
// The source_portfolio_id field is required to identify the portfolio the
// allocation is coming from.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAllocationSourcePortfolioIdRequired Subcode = "ALLOCATION_SOURCE_PORTFOLIO_ID_REQUIRED"

// SubcodeAllocationDestinationPortfolioIdRequired is the subcode ALLOCATION_DESTINATION_PORTFOLIO_ID_REQUIRED.
//
// One or more entries in allocation_legs is missing a destination_portfolio_id.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAllocationDestinationPortfolioIdRequired Subcode = "ALLOCATION_DESTINATION_PORTFOLIO_ID_REQUIRED"

// SubcodeAllocationOrdersMixedSides is the subcode ALLOCATION_ORDERS_MIXED_SIDES.
//
// The orders referenced in order_ids include both buy and sell sides. All orders
// in a single allocation request must share the same side.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationOrdersMixedSides Subcode = "ALLOCATION_ORDERS_MIXED_SIDES"

// SubcodeAllocationOrdersMixedProducts is the subcode ALLOCATION_ORDERS_MIXED_PRODUCTS.
//
// The orders referenced in order_ids span more than one product. All orders in a
// single allocation request must be for the same product_id.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationOrdersMixedProducts Subcode = "ALLOCATION_ORDERS_MIXED_PRODUCTS"

// SubcodeAllocationOrderNotTerminal is the subcode ALLOCATION_ORDER_NOT_TERMINAL.
//
// At least one order in order_ids has not reached a terminal state, so it cannot
// be allocated until it finishes processing.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationOrderNotTerminal Subcode = "ALLOCATION_ORDER_NOT_TERMINAL"

// SubcodeAllocationOrderTooOld is the subcode ALLOCATION_ORDER_TOO_OLD.
//
// At least one order in order_ids exceeds the maximum age allowed for allocation
// and can no longer be allocated.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationOrderTooOld Subcode = "ALLOCATION_ORDER_TOO_OLD"

// SubcodeAllocationOrderAlreadyAllocated is the subcode ALLOCATION_ORDER_ALREADY_ALLOCATED.
//
// At least one order in order_ids has already been allocated and cannot be
// allocated again.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationOrderAlreadyAllocated Subcode = "ALLOCATION_ORDER_ALREADY_ALLOCATED"

// SubcodeAllocationLimitExceeded is the subcode ALLOCATION_LIMIT_EXCEEDED.
//
// The limit field exceeds the maximum number of allocations that can be returned
// in a single request.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAllocationLimitExceeded Subcode = "ALLOCATION_LIMIT_EXCEEDED"
