/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeStakingRequestInvalid is the subcode STAKING_REQUEST_INVALID.
//
// The staking, unstaking, or claim-rewards request contained an invalid parameter,
// such as an unsupported amount, address, option, or allocation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingRequestInvalid Subcode = "STAKING_REQUEST_INVALID"

// SubcodeStakingCurrencyUnsupported is the subcode STAKING_CURRENCY_UNSUPPORTED.
//
// The requested currency or wallet's asset is not supported for this staking
// operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingCurrencyUnsupported Subcode = "STAKING_CURRENCY_UNSUPPORTED"

// SubcodeStakingNotEnabled is the subcode STAKING_NOT_ENABLED.
//
// Wallet-level staking has not been enabled for this portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeStakingNotEnabled Subcode = "STAKING_NOT_ENABLED"

// SubcodeStakingPreconditionFailed is the subcode STAKING_PRECONDITION_FAILED.
//
// The requested staking, unstaking, or claim-rewards action is not currently
// allowed for this wallet.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeStakingPreconditionFailed Subcode = "STAKING_PRECONDITION_FAILED"

// SubcodeStakingServiceUnavailable is the subcode STAKING_SERVICE_UNAVAILABLE.
//
// The staking service could not process the request after repeated attempts.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeStakingServiceUnavailable Subcode = "STAKING_SERVICE_UNAVAILABLE"

// SubcodeStakingValidatorAllocationsNotEnabled is the subcode STAKING_VALIDATOR_ALLOCATIONS_NOT_ENABLED.
//
// The validator_allocations field is not enabled for this portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeStakingValidatorAllocationsNotEnabled Subcode = "STAKING_VALIDATOR_ALLOCATIONS_NOT_ENABLED"

// SubcodeStakingAmountRequired is the subcode STAKING_AMOUNT_REQUIRED.
//
// The amount field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeStakingAmountRequired Subcode = "STAKING_AMOUNT_REQUIRED"

// SubcodeStakingAmountInvalid is the subcode STAKING_AMOUNT_INVALID.
//
// The amount field is not a valid positive decimal number, or does not match the
// sum of the provided validator allocation amounts.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingAmountInvalid Subcode = "STAKING_AMOUNT_INVALID"

// SubcodeStakingInsufficientBalance is the subcode STAKING_INSUFFICIENT_BALANCE.
//
// The wallet has no stakeable, unbondable, or claimable balance available for this
// operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingInsufficientBalance Subcode = "STAKING_INSUFFICIENT_BALANCE"

// SubcodeStakingWalletOrPortfolioInvalid is the subcode STAKING_WALLET_OR_PORTFOLIO_INVALID.
//
// The wallet_id does not exist, is not a valid identifier, or does not belong to
// the given portfolio_id.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingWalletOrPortfolioInvalid Subcode = "STAKING_WALLET_OR_PORTFOLIO_INVALID"

// SubcodeStakingAmountExceedsUnbondableBalance is the subcode STAKING_AMOUNT_EXCEEDS_UNBONDABLE_BALANCE.
//
// The requested unstake amount is greater than the wallet's, validator's, or
// portfolio's available unbondable balance.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingAmountExceedsUnbondableBalance Subcode = "STAKING_AMOUNT_EXCEEDS_UNBONDABLE_BALANCE"

// SubcodeStakingWalletColdAddressNotFound is the subcode STAKING_WALLET_COLD_ADDRESS_NOT_FOUND.
//
// The wallet does not have a cold address on record, which is required to complete
// this staking operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingWalletColdAddressNotFound Subcode = "STAKING_WALLET_COLD_ADDRESS_NOT_FOUND"

// SubcodeStakingNoValidatorsAvailable is the subcode STAKING_NO_VALIDATORS_AVAILABLE.
//
// No Coinbase-operated validators are currently available for the requested
// currency.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingNoValidatorsAvailable Subcode = "STAKING_NO_VALIDATORS_AVAILABLE"

// SubcodeStakingEndDateInvalid is the subcode STAKING_END_DATE_INVALID.
//
// The end_date field is not a valid date in YYYY-MM-DD format.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingEndDateInvalid Subcode = "STAKING_END_DATE_INVALID"

// SubcodeStakingDelegatedAddressNotFound is the subcode STAKING_DELEGATED_ADDRESS_NOT_FOUND.
//
// The wallet has no delegated-to address on record, which is required for this
// currency's staking flow.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingDelegatedAddressNotFound Subcode = "STAKING_DELEGATED_ADDRESS_NOT_FOUND"

// SubcodeStakingCustomAmountNotSupported is the subcode STAKING_CUSTOM_AMOUNT_NOT_SUPPORTED.
//
// A custom amount cannot be specified for this currency and action combination.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingCustomAmountNotSupported Subcode = "STAKING_CUSTOM_AMOUNT_NOT_SUPPORTED"

// SubcodeStakingValidatorAddressNotSupported is the subcode STAKING_VALIDATOR_ADDRESS_NOT_SUPPORTED.
//
// A custom validator_address cannot be specified for this currency.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingValidatorAddressNotSupported Subcode = "STAKING_VALIDATOR_ADDRESS_NOT_SUPPORTED"

// SubcodeStakingValidatorAllocationsUnsupportedCurrency is the subcode STAKING_VALIDATOR_ALLOCATIONS_UNSUPPORTED_CURRENCY.
//
// The validator_allocations field is only supported for ETH unstaking.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingValidatorAllocationsUnsupportedCurrency Subcode = "STAKING_VALIDATOR_ALLOCATIONS_UNSUPPORTED_CURRENCY"

// SubcodeStakingValidatorAllocationIncomplete is the subcode STAKING_VALIDATOR_ALLOCATION_INCOMPLETE.
//
// Each entry in validator_allocations must include both a validator_address and an
// amount.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingValidatorAllocationIncomplete Subcode = "STAKING_VALIDATOR_ALLOCATION_INCOMPLETE"

// SubcodeStakingValidatorNotEligible is the subcode STAKING_VALIDATOR_NOT_ELIGIBLE.
//
// The specified validator_address does not belong to this wallet or is not
// eligible for validator allocations.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingValidatorNotEligible Subcode = "STAKING_VALIDATOR_NOT_ELIGIBLE"

// SubcodeStakingDestinationAddressInvalid is the subcode STAKING_DESTINATION_ADDRESS_INVALID.
//
// The resolved destination address for this staking, unstaking, or claim-rewards
// action is empty or malformed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingDestinationAddressInvalid Subcode = "STAKING_DESTINATION_ADDRESS_INVALID"

// SubcodeStakingActionTypeUnsupported is the subcode STAKING_ACTION_TYPE_UNSUPPORTED.
//
// The action_type field is not a supported staking action (initiate, unstake, or
// claim rewards).
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingActionTypeUnsupported Subcode = "STAKING_ACTION_TYPE_UNSUPPORTED"

// SubcodeStakingUnstakeNotAvailable is the subcode STAKING_UNSTAKE_NOT_AVAILABLE.
//
// A full unstake is not currently available for this wallet.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingUnstakeNotAvailable Subcode = "STAKING_UNSTAKE_NOT_AVAILABLE"

// SubcodeStakingNoEligibleWallets is the subcode STAKING_NO_ELIGIBLE_WALLETS.
//
// No wallet eligible for staking or unstaking was found for the given portfolio_id
// and currency_symbol.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingNoEligibleWallets Subcode = "STAKING_NO_ELIGIBLE_WALLETS"

// SubcodeStakingBalanceNotFound is the subcode STAKING_BALANCE_NOT_FOUND.
//
// No balance could be found for the requested currency_symbol on this portfolio.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeStakingBalanceNotFound Subcode = "STAKING_BALANCE_NOT_FOUND"

// SubcodeStakingAmountExceedsBondableBalance is the subcode STAKING_AMOUNT_EXCEEDS_BONDABLE_BALANCE.
//
// The requested amount to stake exceeds the portfolio's available bondable balance
// for the given currency.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingAmountExceedsBondableBalance Subcode = "STAKING_AMOUNT_EXCEEDS_BONDABLE_BALANCE"

// SubcodeStakingProviderUnstakeNotEnabled is the subcode STAKING_PROVIDER_UNSTAKE_NOT_ENABLED.
//
// Provider-level unstaking (unstaking all validators for a given
// validator_provider) is not enabled for this portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeStakingProviderUnstakeNotEnabled Subcode = "STAKING_PROVIDER_UNSTAKE_NOT_ENABLED"

// SubcodeStakingProviderNoUnbondableBalance is the subcode STAKING_PROVIDER_NO_UNBONDABLE_BALANCE.
//
// No unbondable balance is currently available for the specified
// validator_provider on this portfolio and currency.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeStakingProviderNoUnbondableBalance Subcode = "STAKING_PROVIDER_NO_UNBONDABLE_BALANCE"

// SubcodeStakingIdempotencyKeyRequired is the subcode STAKING_IDEMPOTENCY_KEY_REQUIRED.
//
// The idempotency_key field is required for this staking or unstaking operation.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeStakingIdempotencyKeyRequired Subcode = "STAKING_IDEMPOTENCY_KEY_REQUIRED"

// SubcodeStakingIdempotencyKeyInvalid is the subcode STAKING_IDEMPOTENCY_KEY_INVALID.
//
// The idempotency_key provided is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingIdempotencyKeyInvalid Subcode = "STAKING_IDEMPOTENCY_KEY_INVALID"

// SubcodeStakingCurrencySymbolRequired is the subcode STAKING_CURRENCY_SYMBOL_REQUIRED.
//
// The currency_symbol field is required for this staking or unstaking operation.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeStakingCurrencySymbolRequired Subcode = "STAKING_CURRENCY_SYMBOL_REQUIRED"

// SubcodeStakingAmountValidatorProviderConflict is the subcode STAKING_AMOUNT_VALIDATOR_PROVIDER_CONFLICT.
//
// The amount and validator_provider fields are mutually exclusive; specify at most
// one.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingAmountValidatorProviderConflict Subcode = "STAKING_AMOUNT_VALIDATOR_PROVIDER_CONFLICT"

// SubcodeStakingValidatorProviderRequired is the subcode STAKING_VALIDATOR_PROVIDER_REQUIRED.
//
// The validator_provider field is required for a provider-scoped unstake request.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeStakingValidatorProviderRequired Subcode = "STAKING_VALIDATOR_PROVIDER_REQUIRED"

// SubcodeStakingValidatorProviderNotSupported is the subcode STAKING_VALIDATOR_PROVIDER_NOT_SUPPORTED.
//
// The validator_provider value provided is not a supported provider.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeStakingValidatorProviderNotSupported Subcode = "STAKING_VALIDATOR_PROVIDER_NOT_SUPPORTED"
