/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodePortfolioNotFound is the subcode PORTFOLIO_NOT_FOUND.
//
// No portfolio was found matching the provided portfolio_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodePortfolioNotFound Subcode = "PORTFOLIO_NOT_FOUND"

// SubcodePortfolioIdRequired is the subcode PORTFOLIO_ID_REQUIRED.
//
// The portfolio_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodePortfolioIdRequired Subcode = "PORTFOLIO_ID_REQUIRED"

// SubcodePortfolioTypeUnsupported is the subcode PORTFOLIO_TYPE_UNSUPPORTED.
//
// The portfolio's type does not support this operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePortfolioTypeUnsupported Subcode = "PORTFOLIO_TYPE_UNSUPPORTED"

// SubcodePortfolioIdInvalid is the subcode PORTFOLIO_ID_INVALID.
//
// The portfolio_id is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePortfolioIdInvalid Subcode = "PORTFOLIO_ID_INVALID"

// SubcodePortfolioUsersCursorInvalid is the subcode PORTFOLIO_USERS_CURSOR_INVALID.
//
// The pagination cursor does not match any user in the result set.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePortfolioUsersCursorInvalid Subcode = "PORTFOLIO_USERS_CURSOR_INVALID"

// SubcodePortfolioUsersLimitInvalid is the subcode PORTFOLIO_USERS_LIMIT_INVALID.
//
// The limit parameter for portfolio users is out of the valid range.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePortfolioUsersLimitInvalid Subcode = "PORTFOLIO_USERS_LIMIT_INVALID"

// SubcodePortfolioBalancesInvalidArgument is the subcode PORTFOLIO_BALANCES_INVALID_ARGUMENT.
//
// The portfolio balances request contains an invalid cursor or filter.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePortfolioBalancesInvalidArgument Subcode = "PORTFOLIO_BALANCES_INVALID_ARGUMENT"

// SubcodePortfolioBalancesNotFound is the subcode PORTFOLIO_BALANCES_NOT_FOUND.
//
// No balances were found for the requested portfolio.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodePortfolioBalancesNotFound Subcode = "PORTFOLIO_BALANCES_NOT_FOUND"
