/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeOnchainTransactionRequestInvalid is the subcode ONCHAIN_TRANSACTION_REQUEST_INVALID.
//
// The onchain transaction request failed validation because of an invalid
// parameter, an unsupported wallet type, or a malformed evm_params value.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionRequestInvalid Subcode = "ONCHAIN_TRANSACTION_REQUEST_INVALID"

// SubcodeOnchainAddressGroupRequestInvalid is the subcode ONCHAIN_ADDRESS_GROUP_REQUEST_INVALID.
//
// The onchain address group create, update, or delete request contained invalid
// data and could not be processed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainAddressGroupRequestInvalid Subcode = "ONCHAIN_ADDRESS_GROUP_REQUEST_INVALID"

// SubcodeOnchainTransactionRawUnsignedTxnRequired is the subcode ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_REQUIRED.
//
// The raw_unsigned_txn field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOnchainTransactionRawUnsignedTxnRequired Subcode = "ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_REQUIRED"

// SubcodeOnchainTransactionRawUnsignedTxnInvalid is the subcode ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_INVALID.
//
// The raw_unsigned_txn field is not a valid hex-encoded string.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionRawUnsignedTxnInvalid Subcode = "ONCHAIN_TRANSACTION_RAW_UNSIGNED_TXN_INVALID"

// SubcodeOnchainTransactionEvmParamsRequired is the subcode ONCHAIN_TRANSACTION_EVM_PARAMS_REQUIRED.
//
// The evm_params field is required when the destination wallet is on an EVM-based
// network.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOnchainTransactionEvmParamsRequired Subcode = "ONCHAIN_TRANSACTION_EVM_PARAMS_REQUIRED"

// SubcodeOnchainTransactionEvmParamsInvalid is the subcode ONCHAIN_TRANSACTION_EVM_PARAMS_INVALID.
//
// The evm_params field was provided but the destination wallet is on a non-EVM
// network, such as Solana, where EVM-specific parameters are not supported.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionEvmParamsInvalid Subcode = "ONCHAIN_TRANSACTION_EVM_PARAMS_INVALID"

// SubcodeOnchainTransactionReplacedTransactionIdInvalid is the subcode ONCHAIN_TRANSACTION_REPLACED_TRANSACTION_ID_INVALID.
//
// The replaced_transaction_id field is not a valid transaction identifier.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionReplacedTransactionIdInvalid Subcode = "ONCHAIN_TRANSACTION_REPLACED_TRANSACTION_ID_INVALID"

// SubcodeOnchainTransactionDisableDynamicNonceInvalid is the subcode ONCHAIN_TRANSACTION_DISABLE_DYNAMIC_NONCE_INVALID.
//
// The disable_dynamic_nonce field must be false when replaced_transaction_id is
// set to replace an existing transaction.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionDisableDynamicNonceInvalid Subcode = "ONCHAIN_TRANSACTION_DISABLE_DYNAMIC_NONCE_INVALID"

// SubcodeOnchainTransactionChainIdRequired is the subcode ONCHAIN_TRANSACTION_CHAIN_ID_REQUIRED.
//
// The chain_id field is required within evm_params for transactions on EVM-based
// networks.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOnchainTransactionChainIdRequired Subcode = "ONCHAIN_TRANSACTION_CHAIN_ID_REQUIRED"

// SubcodeOnchainTransactionChainIdInvalid is the subcode ONCHAIN_TRANSACTION_CHAIN_ID_INVALID.
//
// The chain_id field is not a valid integer, or it must be 1 when using the
// Flashbots RPC endpoint.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionChainIdInvalid Subcode = "ONCHAIN_TRANSACTION_CHAIN_ID_INVALID"

// SubcodeOnchainTransactionNetworkNameRequired is the subcode ONCHAIN_TRANSACTION_NETWORK_NAME_REQUIRED.
//
// The network_name field is required when submitting a transaction through a
// custom RPC endpoint.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeOnchainTransactionNetworkNameRequired Subcode = "ONCHAIN_TRANSACTION_NETWORK_NAME_REQUIRED"

// SubcodeOnchainTransactionRpcUrlInvalid is the subcode ONCHAIN_TRANSACTION_RPC_URL_INVALID.
//
// The custom RPC endpoint provided cannot be used, either because the wallet is
// not on an EVM-based network or because the call to that endpoint failed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeOnchainTransactionRpcUrlInvalid Subcode = "ONCHAIN_TRANSACTION_RPC_URL_INVALID"
