/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeAddressBookNotFound is the subcode ADDRESS_BOOK_NOT_FOUND.
//
// The requested address book entry could not be found for the given portfolio_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeAddressBookNotFound Subcode = "ADDRESS_BOOK_NOT_FOUND"

// SubcodeAddressBookInvalidArgument is the subcode ADDRESS_BOOK_INVALID_ARGUMENT.
//
// The address book request contains an invalid argument, such as a malformed
// address or currency_symbol.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAddressBookInvalidArgument Subcode = "ADDRESS_BOOK_INVALID_ARGUMENT"

// SubcodeAddressBookFailedPrecondition is the subcode ADDRESS_BOOK_FAILED_PRECONDITION.
//
// The address book entry could not be created or retrieved because a precondition
// was not met.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeAddressBookFailedPrecondition Subcode = "ADDRESS_BOOK_FAILED_PRECONDITION"

// SubcodeAddressBookAddressRequired is the subcode ADDRESS_BOOK_ADDRESS_REQUIRED.
//
// The address field is required to create an address book entry.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAddressBookAddressRequired Subcode = "ADDRESS_BOOK_ADDRESS_REQUIRED"

// SubcodeAddressBookCurrencySymbolRequired is the subcode ADDRESS_BOOK_CURRENCY_SYMBOL_REQUIRED.
//
// The currency_symbol field is required to create an address book entry.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAddressBookCurrencySymbolRequired Subcode = "ADDRESS_BOOK_CURRENCY_SYMBOL_REQUIRED"

// SubcodeAddressBookNameRequired is the subcode ADDRESS_BOOK_NAME_REQUIRED.
//
// The name field is required to create an address book entry.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeAddressBookNameRequired Subcode = "ADDRESS_BOOK_NAME_REQUIRED"
