/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodePaymentMethodIdRequired is the subcode PAYMENT_METHOD_ID_REQUIRED.
//
// The payment_method_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodePaymentMethodIdRequired Subcode = "PAYMENT_METHOD_ID_REQUIRED"

// SubcodePaymentMethodIdInvalid is the subcode PAYMENT_METHOD_ID_INVALID.
//
// The payment_method_id field is not a valid identifier.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePaymentMethodIdInvalid Subcode = "PAYMENT_METHOD_ID_INVALID"

// SubcodePaymentMethodNotFound is the subcode PAYMENT_METHOD_NOT_FOUND.
//
// The requested payment method could not be found, either because the
// payment_method_id does not exist or it does not belong to the specified
// entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodePaymentMethodNotFound Subcode = "PAYMENT_METHOD_NOT_FOUND"

// SubcodePaymentMethodRequestInvalid is the subcode PAYMENT_METHOD_REQUEST_INVALID.
//
// The payment method request contains an invalid argument.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodePaymentMethodRequestInvalid Subcode = "PAYMENT_METHOD_REQUEST_INVALID"
