/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeWalletIdRequired is the subcode WALLET_ID_REQUIRED.
//
// The wallet_id field is required but was not included in the request.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletIdRequired Subcode = "WALLET_ID_REQUIRED"

// SubcodeWalletIdInvalid is the subcode WALLET_ID_INVALID.
//
// The wallet_id field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletIdInvalid Subcode = "WALLET_ID_INVALID"

// SubcodeWalletTypeNotSupported is the subcode WALLET_TYPE_NOT_SUPPORTED.
//
// The wallet's type does not support this operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletTypeNotSupported Subcode = "WALLET_TYPE_NOT_SUPPORTED"

// SubcodeWalletNotFound is the subcode WALLET_NOT_FOUND.
//
// No wallet was found matching the provided wallet_id, or it does not belong to
// the specified portfolio.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeWalletNotFound Subcode = "WALLET_NOT_FOUND"

// SubcodeWalletServiceUnavailable is the subcode WALLET_SERVICE_UNAVAILABLE.
//
// The service needed to fetch or process wallet data is temporarily unavailable,
// or wallet balances could not be resolved.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeWalletServiceUnavailable Subcode = "WALLET_SERVICE_UNAVAILABLE"

// SubcodeWalletDepositTypeRequired is the subcode WALLET_DEPOSIT_TYPE_REQUIRED.
//
// The deposit_type field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletDepositTypeRequired Subcode = "WALLET_DEPOSIT_TYPE_REQUIRED"

// SubcodeWalletMetadataInvalid is the subcode WALLET_METADATA_INVALID.
//
// The metadata field is not a valid JSON object, or a nested value within it is
// not a JSON object with string values.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletMetadataInvalid Subcode = "WALLET_METADATA_INVALID"

// SubcodeWalletNetworkRequired is the subcode WALLET_NETWORK_REQUIRED.
//
// A network must be specified for crypto deposits because the wallet does not have
// a default network configured.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletNetworkRequired Subcode = "WALLET_NETWORK_REQUIRED"

// SubcodeWalletNotDepositable is the subcode WALLET_NOT_DEPOSITABLE.
//
// The wallet cannot accept deposits.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeWalletNotDepositable Subcode = "WALLET_NOT_DEPOSITABLE"

// SubcodeWalletDepositRequestInvalid is the subcode WALLET_DEPOSIT_REQUEST_INVALID.
//
// The deposit request is invalid or not supported for this wallet.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletDepositRequestInvalid Subcode = "WALLET_DEPOSIT_REQUEST_INVALID"

// SubcodeWalletRequestInvalid is the subcode WALLET_REQUEST_INVALID.
//
// The request contains an invalid argument for this wallet operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletRequestInvalid Subcode = "WALLET_REQUEST_INVALID"

// SubcodeWalletOnchainSymbolsNotAllowed is the subcode WALLET_ONCHAIN_SYMBOLS_NOT_ALLOWED.
//
// The symbols filter cannot be set when the wallet type is ONCHAIN.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletOnchainSymbolsNotAllowed Subcode = "WALLET_ONCHAIN_SYMBOLS_NOT_ALLOWED"

// SubcodeWalletFailedPrecondition is the subcode WALLET_FAILED_PRECONDITION.
//
// The wallet request failed a precondition, such as the wallet not being able to
// accept the requested action.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeWalletFailedPrecondition Subcode = "WALLET_FAILED_PRECONDITION"

// SubcodeWalletNetworkIdRequired is the subcode WALLET_NETWORK_ID_REQUIRED.
//
// The network_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletNetworkIdRequired Subcode = "WALLET_NETWORK_ID_REQUIRED"

// SubcodeWalletNetworkInvalid is the subcode WALLET_NETWORK_INVALID.
//
// The network identifier is malformed. It must be in the format
// {network_id}-{network_type} (e.g. base-mainnet), with no spaces, and each part
// no longer than 20 characters.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletNetworkInvalid Subcode = "WALLET_NETWORK_INVALID"

// SubcodeWalletOnchainSetupUnavailable is the subcode WALLET_ONCHAIN_SETUP_UNAVAILABLE.
//
// Onchain wallet setup for this network family has not been completed yet, and
// must be done through the Prime web application before creating this wallet via
// the API.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeWalletOnchainSetupUnavailable Subcode = "WALLET_ONCHAIN_SETUP_UNAVAILABLE"

// SubcodeWalletNameRequired is the subcode WALLET_NAME_REQUIRED.
//
// The name field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletNameRequired Subcode = "WALLET_NAME_REQUIRED"

// SubcodeWalletSymbolRequired is the subcode WALLET_SYMBOL_REQUIRED.
//
// The symbol field is required for wallet types other than ONCHAIN.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletSymbolRequired Subcode = "WALLET_SYMBOL_REQUIRED"

// SubcodeWalletNetworkFamilyRequired is the subcode WALLET_NETWORK_FAMILY_REQUIRED.
//
// The network_family field is required when wallet_type is ONCHAIN.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletNetworkFamilyRequired Subcode = "WALLET_NETWORK_FAMILY_REQUIRED"

// SubcodeWalletNetworkFamilyNotAllowed is the subcode WALLET_NETWORK_FAMILY_NOT_ALLOWED.
//
// The network_family field must not be set when wallet_type is not ONCHAIN.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletNetworkFamilyNotAllowed Subcode = "WALLET_NETWORK_FAMILY_NOT_ALLOWED"

// SubcodeWalletBalancesLimitInvalid is the subcode WALLET_BALANCES_LIMIT_INVALID.
//
// The limit field is outside the allowed range for this request.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletBalancesLimitInvalid Subcode = "WALLET_BALANCES_LIMIT_INVALID"

// SubcodeWalletVisibilityStatusesInvalid is the subcode WALLET_VISIBILITY_STATUSES_INVALID.
//
// The visibility_statuses filter contains more values than are allowed.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletVisibilityStatusesInvalid Subcode = "WALLET_VISIBILITY_STATUSES_INVALID"

// SubcodeWalletNetworkTypeRequired is the subcode WALLET_NETWORK_TYPE_REQUIRED.
//
// The type field on the network object is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletNetworkTypeRequired Subcode = "WALLET_NETWORK_TYPE_REQUIRED"

// SubcodeWalletNetworkTypeNotSupported is the subcode WALLET_NETWORK_TYPE_NOT_SUPPORTED.
//
// The network type portion of network_id is not a supported value for this
// environment.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletNetworkTypeNotSupported Subcode = "WALLET_NETWORK_TYPE_NOT_SUPPORTED"

// SubcodeWalletExternalIdInvalid is the subcode WALLET_EXTERNAL_ID_INVALID.
//
// The external_id field is not valid UTF-8, or exceeds 255 bytes.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletExternalIdInvalid Subcode = "WALLET_EXTERNAL_ID_INVALID"

// SubcodeWalletAmountRequired is the subcode WALLET_AMOUNT_REQUIRED.
//
// The amount field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletAmountRequired Subcode = "WALLET_AMOUNT_REQUIRED"

// SubcodeWalletIdempotencyKeyRequired is the subcode WALLET_IDEMPOTENCY_KEY_REQUIRED.
//
// The idempotency_key field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletIdempotencyKeyRequired Subcode = "WALLET_IDEMPOTENCY_KEY_REQUIRED"

// SubcodeWalletIdempotencyKeyInvalid is the subcode WALLET_IDEMPOTENCY_KEY_INVALID.
//
// The idempotency_key field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletIdempotencyKeyInvalid Subcode = "WALLET_IDEMPOTENCY_KEY_INVALID"

// SubcodeWalletCurrencySymbolRequired is the subcode WALLET_CURRENCY_SYMBOL_REQUIRED.
//
// The currency_symbol field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletCurrencySymbolRequired Subcode = "WALLET_CURRENCY_SYMBOL_REQUIRED"

// SubcodeWalletTransferDestinationRequired is the subcode WALLET_TRANSFER_DESTINATION_REQUIRED.
//
// The destination wallet ID is required for an internal wallet transfer.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletTransferDestinationRequired Subcode = "WALLET_TRANSFER_DESTINATION_REQUIRED"

// SubcodeWalletTransferDestinationInvalid is the subcode WALLET_TRANSFER_DESTINATION_INVALID.
//
// The destination wallet ID is not a valid UUID, or is the same as the source
// wallet_id.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletTransferDestinationInvalid Subcode = "WALLET_TRANSFER_DESTINATION_INVALID"

// SubcodeWalletPortfolioCreditFrozen is the subcode WALLET_PORTFOLIO_CREDIT_FROZEN.
//
// The portfolio's credit is frozen, preventing this transaction. Contact support
// to resolve this.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeWalletPortfolioCreditFrozen Subcode = "WALLET_PORTFOLIO_CREDIT_FROZEN"

// SubcodeWalletDestinationTypeRequired is the subcode WALLET_DESTINATION_TYPE_REQUIRED.
//
// The destination_type field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletDestinationTypeRequired Subcode = "WALLET_DESTINATION_TYPE_REQUIRED"

// SubcodeWalletDestinationTypeInvalid is the subcode WALLET_DESTINATION_TYPE_INVALID.
//
// The destination_type field is not a supported value for this operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeWalletDestinationTypeInvalid Subcode = "WALLET_DESTINATION_TYPE_INVALID"

// SubcodeWalletCounterpartyIdRequired is the subcode WALLET_COUNTERPARTY_ID_REQUIRED.
//
// The counterparty_id field is required when destination_type is a counterparty
// destination.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeWalletCounterpartyIdRequired Subcode = "WALLET_COUNTERPARTY_ID_REQUIRED"
