/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeActivityNotFound is the subcode ACTIVITY_NOT_FOUND.
//
// The requested activity could not be found, either because the activity_id does
// not exist or it does not belong to the specified portfolio_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeActivityNotFound Subcode = "ACTIVITY_NOT_FOUND"

// SubcodeActivityRequestInvalid is the subcode ACTIVITY_REQUEST_INVALID.
//
// The activity request contains an invalid argument, such as a malformed filter or
// identifier.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeActivityRequestInvalid Subcode = "ACTIVITY_REQUEST_INVALID"

// SubcodeActivityAccessDenied is the subcode ACTIVITY_ACCESS_DENIED.
//
// You do not have permission to access the requested activity data for the given
// entity or portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeActivityAccessDenied Subcode = "ACTIVITY_ACCESS_DENIED"

// SubcodeActivityCategoryInvalid is the subcode ACTIVITY_CATEGORY_INVALID.
//
// The categories field contains a value that is not a supported activity category.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeActivityCategoryInvalid Subcode = "ACTIVITY_CATEGORY_INVALID"

// SubcodeActivityTimeRangeInvalid is the subcode ACTIVITY_TIME_RANGE_INVALID.
//
// The start_time or end_time field is not a valid RFC 3339 timestamp, or end_time
// is earlier than start_time.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeActivityTimeRangeInvalid Subcode = "ACTIVITY_TIME_RANGE_INVALID"

// SubcodeActivityStatusInvalid is the subcode ACTIVITY_STATUS_INVALID.
//
// The statuses field contains a value that is not a supported activity status.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeActivityStatusInvalid Subcode = "ACTIVITY_STATUS_INVALID"

// SubcodeActivityPortfolioIdMismatch is the subcode ACTIVITY_PORTFOLIO_ID_MISMATCH.
//
// The requested activity exists but does not belong to the portfolio_id provided
// in the request.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeActivityPortfolioIdMismatch Subcode = "ACTIVITY_PORTFOLIO_ID_MISMATCH"
