/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeFinancingStartDateRequired is the subcode FINANCING_START_DATE_REQUIRED.
//
// The start_date field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeFinancingStartDateRequired Subcode = "FINANCING_START_DATE_REQUIRED"

// SubcodeFinancingEndDateRequired is the subcode FINANCING_END_DATE_REQUIRED.
//
// The end_date field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeFinancingEndDateRequired Subcode = "FINANCING_END_DATE_REQUIRED"

// SubcodeFinancingStartDateInvalid is the subcode FINANCING_START_DATE_INVALID.
//
// The start_date value is not a valid RFC 3339 timestamp.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFinancingStartDateInvalid Subcode = "FINANCING_START_DATE_INVALID"

// SubcodeFinancingEndDateInvalid is the subcode FINANCING_END_DATE_INVALID.
//
// The end_date value is not a valid RFC 3339 timestamp.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFinancingEndDateInvalid Subcode = "FINANCING_END_DATE_INVALID"

// SubcodeFinancingPortfolioMarginNotEnabled is the subcode FINANCING_PORTFOLIO_MARGIN_NOT_ENABLED.
//
// Portfolio margin is not enabled for the requested portfolio or entity, so this
// financing endpoint cannot return data.
// HTTP status: 401. Error code: AUTHENTICATION_FAILED.
const SubcodeFinancingPortfolioMarginNotEnabled Subcode = "FINANCING_PORTFOLIO_MARGIN_NOT_ENABLED"

// SubcodeFinancingAccrualsInvalidArgument is the subcode FINANCING_ACCRUALS_INVALID_ARGUMENT.
//
// One or more parameters in the interest accruals request are invalid, such as
// entity_id, portfolio_id, start_date, or end_date.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFinancingAccrualsInvalidArgument Subcode = "FINANCING_ACCRUALS_INVALID_ARGUMENT"

// SubcodeFinancingAccrualsDateInvalid is the subcode FINANCING_ACCRUALS_DATE_INVALID.
//
// The start_date to end_date range provided for interest accruals is not valid for
// the requested portfolio.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFinancingAccrualsDateInvalid Subcode = "FINANCING_ACCRUALS_DATE_INVALID"

// SubcodeBuyingPowerBaseCurrencyRequired is the subcode BUYING_POWER_BASE_CURRENCY_REQUIRED.
//
// The base_currency field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeBuyingPowerBaseCurrencyRequired Subcode = "BUYING_POWER_BASE_CURRENCY_REQUIRED"

// SubcodeBuyingPowerQuoteCurrencyRequired is the subcode BUYING_POWER_QUOTE_CURRENCY_REQUIRED.
//
// The quote_currency field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeBuyingPowerQuoteCurrencyRequired Subcode = "BUYING_POWER_QUOTE_CURRENCY_REQUIRED"

// SubcodeBuyingPowerCurrencyInvalid is the subcode BUYING_POWER_CURRENCY_INVALID.
//
// The requested currency pair is not valid or not supported for buying power.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeBuyingPowerCurrencyInvalid Subcode = "BUYING_POWER_CURRENCY_INVALID"

// SubcodeBuyingPowerNotFound is the subcode BUYING_POWER_NOT_FOUND.
//
// No buying power data was found for the requested portfolio and currency pair.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeBuyingPowerNotFound Subcode = "BUYING_POWER_NOT_FOUND"

// SubcodeBuyingPowerPermissionDenied is the subcode BUYING_POWER_PERMISSION_DENIED.
//
// You do not have permission to view buying power for the requested portfolio and
// currency pair.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeBuyingPowerPermissionDenied Subcode = "BUYING_POWER_PERMISSION_DENIED"

// SubcodeBuyingPowerFailedPrecondition is the subcode BUYING_POWER_FAILED_PRECONDITION.
//
// The buying power request failed a precondition, such as the portfolio not being
// in a state that supports the requested currency pair.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeBuyingPowerFailedPrecondition Subcode = "BUYING_POWER_FAILED_PRECONDITION"

// SubcodeCrossMarginNotEnabled is the subcode CROSS_MARGIN_NOT_ENABLED.
//
// Cross margin is not enabled for the requested entity.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeCrossMarginNotEnabled Subcode = "CROSS_MARGIN_NOT_ENABLED"

// SubcodeCrossMarginInvalidArgument is the subcode CROSS_MARGIN_INVALID_ARGUMENT.
//
// The cross margin or funding settings request contains an invalid argument, such
// as a portfolio_id, entity_id, or liquidation_id that does not belong to the
// specified entity.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeCrossMarginInvalidArgument Subcode = "CROSS_MARGIN_INVALID_ARGUMENT"

// SubcodeCrossMarginFailedPrecondition is the subcode CROSS_MARGIN_FAILED_PRECONDITION.
//
// The cross margin or funding settings request failed a precondition, such as the
// entity or portfolio not being in a state that supports the requested operation.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeCrossMarginFailedPrecondition Subcode = "CROSS_MARGIN_FAILED_PRECONDITION"

// SubcodeLocateDateInvalid is the subcode LOCATE_DATE_INVALID.
//
// The locate_date value is not a valid YYYY-MM-DD date.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeLocateDateInvalid Subcode = "LOCATE_DATE_INVALID"

// SubcodeLocateRequestInvalid is the subcode LOCATE_REQUEST_INVALID.
//
// The stock locate request is invalid — for example, both locate_date and
// locate_ids are missing, or the requested locate_date is in the past or too far
// in the future.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeLocateRequestInvalid Subcode = "LOCATE_REQUEST_INVALID"

// SubcodeLocateIdsInvalid is the subcode LOCATE_IDS_INVALID.
//
// One or more values in locate_ids are not valid UUIDs.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeLocateIdsInvalid Subcode = "LOCATE_IDS_INVALID"

// SubcodeLocateFailedPrecondition is the subcode LOCATE_FAILED_PRECONDITION.
//
// The stock locate request failed a precondition, such as no availability for the
// requested currency or portfolio margin not being enabled.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeLocateFailedPrecondition Subcode = "LOCATE_FAILED_PRECONDITION"

// SubcodeLocateDateRequired is the subcode LOCATE_DATE_REQUIRED.
//
// The locate_date field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeLocateDateRequired Subcode = "LOCATE_DATE_REQUIRED"

// SubcodeMarginSummaryRangeInvalid is the subcode MARGIN_SUMMARY_RANGE_INVALID.
//
// The requested start_date to end_date range exceeds the maximum trailing period
// of 3 months for margin summaries.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeMarginSummaryRangeInvalid Subcode = "MARGIN_SUMMARY_RANGE_INVALID"

// SubcodeFinancingServiceUnavailable is the subcode FINANCING_SERVICE_UNAVAILABLE.
//
// Financing data cannot be retrieved right now. This is a service-wide condition
// unrelated to your request or account.
// HTTP status: 503. Error code: SERVICE_UNAVAILABLE.
const SubcodeFinancingServiceUnavailable Subcode = "FINANCING_SERVICE_UNAVAILABLE"

// SubcodeMarginConversionRequestInvalid is the subcode MARGIN_CONVERSION_REQUEST_INVALID.
//
// One or more parameters in the margin conversions request are invalid, such as
// portfolio_id, start_date, or end_date.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeMarginConversionRequestInvalid Subcode = "MARGIN_CONVERSION_REQUEST_INVALID"

// SubcodeLocateAvailabilityNotFound is the subcode LOCATE_AVAILABILITY_NOT_FOUND.
//
// No locate availability data was found for the requested entity and date.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeLocateAvailabilityNotFound Subcode = "LOCATE_AVAILABILITY_NOT_FOUND"

// SubcodeMarginInformationRequestInvalid is the subcode MARGIN_INFORMATION_REQUEST_INVALID.
//
// One or more parameters in the margin information request are invalid, such as
// entity_id.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeMarginInformationRequestInvalid Subcode = "MARGIN_INFORMATION_REQUEST_INVALID"

// SubcodeMarginConversionFailedPrecondition is the subcode MARGIN_CONVERSION_FAILED_PRECONDITION.
//
// The margin conversions request failed a precondition, such as the portfolio not
// being in a state that supports margin conversions.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeMarginConversionFailedPrecondition Subcode = "MARGIN_CONVERSION_FAILED_PRECONDITION"

// SubcodeMarginSummaryFailedPrecondition is the subcode MARGIN_SUMMARY_FAILED_PRECONDITION.
//
// The margin summaries request failed a precondition, such as the entity not being
// in a state that supports margin summaries.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeMarginSummaryFailedPrecondition Subcode = "MARGIN_SUMMARY_FAILED_PRECONDITION"

// SubcodeFundingSettingsExcessTargetAmountInvalid is the subcode FUNDING_SETTINGS_EXCESS_TARGET_AMOUNT_INVALID.
//
// The excess_funds_target_amount field is missing, is not a valid decimal number,
// or is negative.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFundingSettingsExcessTargetAmountInvalid Subcode = "FUNDING_SETTINGS_EXCESS_TARGET_AMOUNT_INVALID"

// SubcodeFinancingWithdrawalPowerInvalidArgument is the subcode FINANCING_WITHDRAWAL_POWER_INVALID_ARGUMENT.
//
// One or more parameters in the withdrawal power request are invalid, such as
// portfolio_id or symbol.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFinancingWithdrawalPowerInvalidArgument Subcode = "FINANCING_WITHDRAWAL_POWER_INVALID_ARGUMENT"

// SubcodeFinancingWithdrawalPowerSymbolRequired is the subcode FINANCING_WITHDRAWAL_POWER_SYMBOL_REQUIRED.
//
// The symbol field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeFinancingWithdrawalPowerSymbolRequired Subcode = "FINANCING_WITHDRAWAL_POWER_SYMBOL_REQUIRED"

// SubcodeFinancingPtcDisabledForPmEntity is the subcode FINANCING_PTC_DISABLED_FOR_PM_ENTITY.
//
// Post-trade credit information is not available for this portfolio because its
// entity has portfolio margin enabled.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeFinancingPtcDisabledForPmEntity Subcode = "FINANCING_PTC_DISABLED_FOR_PM_ENTITY"

// SubcodeFinancingFailedPrecondition is the subcode FINANCING_FAILED_PRECONDITION.
//
// The interest accruals request failed a precondition, such as an invalid date
// range for the requested entity or portfolio.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeFinancingFailedPrecondition Subcode = "FINANCING_FAILED_PRECONDITION"

// SubcodeFinancingAccrualsRangeExceeded is the subcode FINANCING_ACCRUALS_RANGE_EXCEEDED.
//
// The requested start_date to end_date range exceeds the maximum trailing period
// of 12 months for interest accruals.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeFinancingAccrualsRangeExceeded Subcode = "FINANCING_ACCRUALS_RANGE_EXCEEDED"

// SubcodeTieredPricingEffectiveAtInvalid is the subcode TIERED_PRICING_EFFECTIVE_AT_INVALID.
//
// The effective_at value is not a valid RFC 3339 timestamp.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTieredPricingEffectiveAtInvalid Subcode = "TIERED_PRICING_EFFECTIVE_AT_INVALID"

// SubcodeTieredPricingRequestInvalid is the subcode TIERED_PRICING_REQUEST_INVALID.
//
// One or more parameters in the tiered pricing request are invalid, such as
// entity_id or effective_at.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeTieredPricingRequestInvalid Subcode = "TIERED_PRICING_REQUEST_INVALID"

// SubcodeTieredPricingFailedPrecondition is the subcode TIERED_PRICING_FAILED_PRECONDITION.
//
// The tiered pricing request failed a precondition, such as the entity not being
// enabled for tiered pricing.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeTieredPricingFailedPrecondition Subcode = "TIERED_PRICING_FAILED_PRECONDITION"

// SubcodeLocateSymbolRequired is the subcode LOCATE_SYMBOL_REQUIRED.
//
// The symbol field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeLocateSymbolRequired Subcode = "LOCATE_SYMBOL_REQUIRED"

// SubcodeLocateAmountRequired is the subcode LOCATE_AMOUNT_REQUIRED.
//
// The amount field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeLocateAmountRequired Subcode = "LOCATE_AMOUNT_REQUIRED"

// SubcodeRewardsApiFeatureDisabled is the subcode REWARDS_API_FEATURE_DISABLED.
//
// The Rewards Rate API is not enabled for this entity or portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeRewardsApiFeatureDisabled Subcode = "REWARDS_API_FEATURE_DISABLED"

// SubcodeRewardsRequestInvalid is the subcode REWARDS_REQUEST_INVALID.
//
// The rewards rate request is invalid.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeRewardsRequestInvalid Subcode = "REWARDS_REQUEST_INVALID"

// SubcodeRewardsEntityNotEnrolled is the subcode REWARDS_ENTITY_NOT_ENROLLED.
//
// The entity is not enrolled in Prime Rewards.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeRewardsEntityNotEnrolled Subcode = "REWARDS_ENTITY_NOT_ENROLLED"

// SubcodeConversionFeeFeatureDisabled is the subcode CONVERSION_FEE_FEATURE_DISABLED.
//
// The conversion fees API is not enabled for this entity.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeConversionFeeFeatureDisabled Subcode = "CONVERSION_FEE_FEATURE_DISABLED"

// SubcodeConversionFeeNotEnabledForOrg is the subcode CONVERSION_FEE_NOT_ENABLED_FOR_ORG.
//
// Stablecoin conversion fee configuration has not been set up for this entity's
// owning organization.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeConversionFeeNotEnabledForOrg Subcode = "CONVERSION_FEE_NOT_ENABLED_FOR_ORG"

// SubcodeConversionDestinationInvalid is the subcode CONVERSION_DESTINATION_INVALID.
//
// The destination field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeConversionDestinationInvalid Subcode = "CONVERSION_DESTINATION_INVALID"

// SubcodeConversionIdempotencyKeyInvalid is the subcode CONVERSION_IDEMPOTENCY_KEY_INVALID.
//
// The idempotency_key field is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeConversionIdempotencyKeyInvalid Subcode = "CONVERSION_IDEMPOTENCY_KEY_INVALID"

// SubcodeConversionAmountInvalid is the subcode CONVERSION_AMOUNT_INVALID.
//
// The amount field is not a valid decimal number.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeConversionAmountInvalid Subcode = "CONVERSION_AMOUNT_INVALID"

// SubcodeConversionSourceSymbolRequired is the subcode CONVERSION_SOURCE_SYMBOL_REQUIRED.
//
// The source_symbol field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeConversionSourceSymbolRequired Subcode = "CONVERSION_SOURCE_SYMBOL_REQUIRED"

// SubcodeConversionDestinationRequired is the subcode CONVERSION_DESTINATION_REQUIRED.
//
// The destination field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeConversionDestinationRequired Subcode = "CONVERSION_DESTINATION_REQUIRED"

// SubcodeConversionRequestInvalid is the subcode CONVERSION_REQUEST_INVALID.
//
// The conversion request was rejected as invalid, for example due to an
// unsupported asset pair or a duplicate transaction.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeConversionRequestInvalid Subcode = "CONVERSION_REQUEST_INVALID"

// SubcodeConversionFailedPrecondition is the subcode CONVERSION_FAILED_PRECONDITION.
//
// The conversion could not be completed because a required condition was not met,
// such as insufficient available balance in the source wallet.
// HTTP status: 400. Error code: FAILED_PRECONDITION.
const SubcodeConversionFailedPrecondition Subcode = "CONVERSION_FAILED_PRECONDITION"

// SubcodeConversionPermissionDenied is the subcode CONVERSION_PERMISSION_DENIED.
//
// You do not have permission to convert funds using the specified wallet_id or
// portfolio.
// HTTP status: 403. Error code: PERMISSION_DENIED.
const SubcodeConversionPermissionDenied Subcode = "CONVERSION_PERMISSION_DENIED"

// SubcodeConversionWalletNotFound is the subcode CONVERSION_WALLET_NOT_FOUND.
//
// The wallet identified by wallet_id or destination could not be found, or does
// not belong to the specified portfolio_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeConversionWalletNotFound Subcode = "CONVERSION_WALLET_NOT_FOUND"
