/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeCommissionProductIdInvalid is the subcode COMMISSION_PRODUCT_ID_INVALID.
//
// The product_id is not a recognized trading pair.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeCommissionProductIdInvalid Subcode = "COMMISSION_PRODUCT_ID_INVALID"

// SubcodeCommissionTradingNotEnabled is the subcode COMMISSION_TRADING_NOT_ENABLED.
//
// The portfolio_id belongs to a portfolio that is not enabled for trading, so a
// trading commission rate cannot be calculated for it.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeCommissionTradingNotEnabled Subcode = "COMMISSION_TRADING_NOT_ENABLED"
