/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors

// SubcodeEntityIdRequired is the subcode ENTITY_ID_REQUIRED.
//
// The entity_id field is required but was not provided.
// HTTP status: 400. Error code: REQUIRED_FIELD_MISSING.
const SubcodeEntityIdRequired Subcode = "ENTITY_ID_REQUIRED"

// SubcodeEntityIdInvalid is the subcode ENTITY_ID_INVALID.
//
// The entity_id is not a valid UUID.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeEntityIdInvalid Subcode = "ENTITY_ID_INVALID"

// SubcodeEntityNotFound is the subcode ENTITY_NOT_FOUND.
//
// No entity was found matching the provided entity_id.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeEntityNotFound Subcode = "ENTITY_NOT_FOUND"

// SubcodeEntityBalancesLimitInvalid is the subcode ENTITY_BALANCES_LIMIT_INVALID.
//
// The limit parameter for entity balances is out of the valid range.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeEntityBalancesLimitInvalid Subcode = "ENTITY_BALANCES_LIMIT_INVALID"

// SubcodeEntityBalancesInvalidArgument is the subcode ENTITY_BALANCES_INVALID_ARGUMENT.
//
// The entity balances request contains an invalid cursor or filter.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeEntityBalancesInvalidArgument Subcode = "ENTITY_BALANCES_INVALID_ARGUMENT"

// SubcodeEntityBalancesNotFound is the subcode ENTITY_BALANCES_NOT_FOUND.
//
// No balances were found for the requested entity.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeEntityBalancesNotFound Subcode = "ENTITY_BALANCES_NOT_FOUND"

// SubcodeEntityPositionLimitInvalid is the subcode ENTITY_POSITION_LIMIT_INVALID.
//
// The limit field must be greater than 0 and no greater than the maximum allowed
// value.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeEntityPositionLimitInvalid Subcode = "ENTITY_POSITION_LIMIT_INVALID"

// SubcodeEntityPositionNotFound is the subcode ENTITY_POSITION_NOT_FOUND.
//
// No position data was found for the given entity or portfolio.
// HTTP status: 404. Error code: RESOURCE_NOT_FOUND.
const SubcodeEntityPositionNotFound Subcode = "ENTITY_POSITION_NOT_FOUND"

// SubcodeEntityPositionInvalidArgument is the subcode ENTITY_POSITION_INVALID_ARGUMENT.
//
// The position request contains an invalid argument, such as a malformed
// portfolio_id or other filter.
// HTTP status: 400. Error code: VALIDATION_ERROR.
const SubcodeEntityPositionInvalidArgument Subcode = "ENTITY_POSITION_INVALID_ARGUMENT"
