/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

const generatedHeader = `/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by tools/gen_errors; DO NOT EDIT.

package errors
`

// Longest-prefix-first mapping from subcode name to domain file stem.
var domainPrefixes = []struct {
	prefix string
	domain string
}{
	{"ADDRESS_BOOK_", "addressbook"},
	{"ADVANCED_TRANSFER_", "advanced_transfer"},
	{"ONCHAIN_", "onchain"},
	{"PAYMENT_METHOD_", "paymentmethod"},
	{"CROSS_MARGIN_", "financing"},
	{"BUYING_POWER_", "financing"},
	{"ENTITY_POSITION_", "entity"},
	{"ENTITY_", "entity"},
	{"PORTFOLIO_", "portfolio"},
	{"ALLOCATION_", "allocation"},
	{"TRANSACTION_", "transaction"},
	{"FINANCING_", "financing"},
	{"MARGIN_", "financing"},
	{"LOCATE_", "financing"},
	{"FUNDING_", "financing"},
	{"TIERED_", "financing"},
	{"REWARDS_", "financing"},
	{"CONVERSION_", "financing"},
	{"ORDER_", "order"},
	{"WALLET_", "wallet"},
	{"STAKING_", "staking"},
	{"FCM_", "futures"},
	{"PRODUCT_", "product"},
	{"CANDLE_", "product"},
	{"MARKET_", "product"},
	{"ACTIVITY_", "activity"},
	{"ASSET_", "asset"},
	{"COMMISSION_", "commission"},
	{"AUTH_", "common"},
	{"SERVER_", "common"},
	{"MTLS_", "common"},
	{"ENDPOINT_", "common"},
	{"API_", "common"},
}

func domainForSubcode(name string) (string, error) {
	for _, p := range domainPrefixes {
		if strings.HasPrefix(name, p.prefix) {
			return p.domain, nil
		}
	}
	return "", fmt.Errorf("no domain mapping for subcode %s", name)
}

func toExportedIdent(prefix, name string) string {
	parts := strings.Split(name, "_")
	var b strings.Builder
	b.WriteString(prefix)
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(titleWord(p))
	}
	return b.String()
}

func titleWord(s string) string {
	s = strings.ToLower(s)
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func wrapComment(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}
	var lines []string
	var cur strings.Builder
	for _, w := range words {
		if cur.Len() == 0 {
			cur.WriteString(w)
			continue
		}
		if cur.Len()+1+len(w) > width {
			lines = append(lines, cur.String())
			cur.Reset()
			cur.WriteString(w)
			continue
		}
		cur.WriteByte(' ')
		cur.WriteString(w)
	}
	if cur.Len() > 0 {
		lines = append(lines, cur.String())
	}
	return lines
}

func writeGodoc(b *strings.Builder, ident, summary string, extra ...string) {
	fmt.Fprintf(b, "// %s %s\n", ident, summary)
	fmt.Fprintf(b, "//\n")
	for _, line := range extra {
		if line == "" {
			continue
		}
		for _, wrapped := range wrapComment(line, 80) {
			fmt.Fprintf(b, "// %s\n", wrapped)
		}
	}
}

func generate(outDir string, codes []errorCodeDef, subcodes []subcodeDef) ([]string, error) {
	var written []string

	codeFile := filepath.Join(outDir, "code_gen.go")
	if err := os.WriteFile(codeFile, []byte(renderErrorCodes(codes)), 0o644); err != nil {
		return nil, err
	}
	written = append(written, codeFile)

	byDomain := map[string][]subcodeDef{}
	for _, s := range subcodes {
		d, err := domainForSubcode(s.Name)
		if err != nil {
			return nil, err
		}
		byDomain[d] = append(byDomain[d], s)
	}

	domains := make([]string, 0, len(byDomain))
	for d := range byDomain {
		domains = append(domains, d)
	}
	sort.Strings(domains)

	for _, d := range domains {
		name := filepath.Join(outDir, "subcode_"+d+"_gen.go")
		if err := os.WriteFile(name, []byte(renderSubcodes(d, byDomain[d])), 0o644); err != nil {
			return nil, err
		}
		written = append(written, name)
	}

	infoFile := filepath.Join(outDir, "info_gen.go")
	if err := os.WriteFile(infoFile, []byte(renderInfo(codes, subcodes)), 0o644); err != nil {
		return nil, err
	}
	written = append(written, infoFile)

	return written, nil
}

func renderErrorCodes(codes []errorCodeDef) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteByte('\n')
	for i, c := range codes {
		ident := toExportedIdent("ErrorCode", c.Name)
		if i > 0 {
			b.WriteByte('\n')
		}
		writeGodoc(&b, ident, "is the error code "+c.Name+".",
			c.Description,
			fmt.Sprintf("Typical HTTP status: %d.", c.HTTPStatus),
		)
		fmt.Fprintf(&b, "const %s ErrorCode = %q\n", ident, c.Name)
	}
	return b.String()
}

func renderSubcodes(domain string, subcodes []subcodeDef) string {
	_ = domain
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteByte('\n')
	for i, s := range subcodes {
		ident := toExportedIdent("Subcode", s.Name)
		if i > 0 {
			b.WriteByte('\n')
		}
		writeGodoc(&b, ident, "is the subcode "+s.Name+".",
			s.Description,
			fmt.Sprintf("HTTP status: %d. Error code: %s.", s.HTTPStatus, s.ErrorCode),
		)
		fmt.Fprintf(&b, "const %s Subcode = %q\n", ident, s.Name)
	}
	return b.String()
}

func renderInfo(codes []errorCodeDef, subcodes []subcodeDef) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString(`
func init() {
	errorCodeInfo = map[ErrorCode]ErrorCodeInfo{
`)
	for _, c := range codes {
		ident := toExportedIdent("ErrorCode", c.Name)
		fmt.Fprintf(&b, "\t\t%s: {Code: %s, HTTPStatus: %d, Description: %q},\n",
			ident, ident, c.HTTPStatus, c.Description)
	}
	b.WriteString("\t}\n")
	b.WriteString("\tsubcodeInfo = map[Subcode]SubcodeInfo{\n")
	for _, s := range subcodes {
		ident := toExportedIdent("Subcode", s.Name)
		codeIdent := toExportedIdent("ErrorCode", s.ErrorCode)
		fmt.Fprintf(&b, "\t\t%s: {Subcode: %s, ErrorCode: %s, HTTPStatus: %d, Description: %q},\n",
			ident, ident, codeIdent, s.HTTPStatus, s.Description)
	}
	b.WriteString("\t}\n}\n")
	return b.String()
}
